[tool.ruff]
line-length = 88
target-version = "py312"

[tool.ruff.lint]
# Seleciona as regras que o linter deve verificar.
# "F": Pyflakes (erros de lógica, como variáveis não usadas)
# "E": pycodestyle (erros de estilo, como indentação errada)
# "W": pycodestyle (avisos de estilo, como linhas em branco extras)
# "I": isort (organização automática dos imports)
# A regra "UP" (pyupgrade), que era a mais agressiva, foi removida.
select = ["F", "E", "W", "I"]

# Ignora a regra de "linha muito longa", que já é controlada pelo "line-length".
ignore = ["E501"]