[tool.pylint.main]
# Define a nota mínima para o CI passar
fail-under = 8.0

# Ignora a pasta de migrações
ignore = ["migrations"]

# Ajuda o pylint a encontrar os módulos dentro de 'src'
source-roots = ["src"]

# Desativa avisos comuns que não se aplicam bem ao FastAPI/Pydantic
# R0903: too-few-public-methods (chato para Schemas)
# C0103: invalid-name (permite 'db', 'id', 'q')
# E0401: import-error (pode acontecer com 'src')
# W0613: unused-argument (necessário para dependências do FastAPI)
# R0913: too-many-arguments (chato para rotas FastAPI e fixtures pytest)
# W0613: redefined-outer-name (para as fixtures do Pytest)
# R0917: too-many-positional-arguments (também para fixtures/rotas)
# E1102: Corrige os falsos positivos E1102 (func.now e func.count do SQLAlchemy)
disable = [
    "R0903",
    "C0103",
    "E0401",
    "W0613",
    "R0913", 
    "W0621",
    "R0917",
    "E1102"
]

