"""add unique constraint in name column in folder table

Revision ID: 62ba21f0999e
Revises: 7d3591000d42
Create Date: 2025-09-18 17:36:56.558497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62ba21f0999e'
down_revision: Union[str, Sequence[str], None] = '7d3591000d42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_folders_name'), table_name='folders')
    op.create_index(op.f('ix_folders_name'), 'folders', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_folders_name'), table_name='folders')
    op.create_index(op.f('ix_folders_name'), 'folders', ['name'], unique=False)
    # ### end Alembic commands ###
