"""add user id to all models

Revision ID: 907e05488f5b
Revises: 5f65d27b84c7
Create Date: 2025-10-23 00:15:19.444147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '907e05488f5b'
down_revision: Union[str, Sequence[str], None] = '5f65d27b84c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notebooks', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_notebooks_user_id'), 'notebooks', ['user_id'], unique=False)
    op.add_column('notes', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_notes_user_id'), 'notes', ['user_id'], unique=False)
    op.add_column('tags', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_tags_user_id'), 'tags', ['user_id'], unique=False)
    op.add_column('templates', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_templates_user_id'), 'templates', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_templates_user_id'), table_name='templates')
    op.drop_column('templates', 'user_id')
    op.drop_index(op.f('ix_tags_user_id'), table_name='tags')
    op.drop_column('tags', 'user_id')
    op.drop_index(op.f('ix_notes_user_id'), table_name='notes')
    op.drop_column('notes', 'user_id')
    op.drop_index(op.f('ix_notebooks_user_id'), table_name='notebooks')
    op.drop_column('notebooks', 'user_id')
    # ### end Alembic commands ###
