"""fix unique constraints and cascade delete

Revision ID: a0f4b7cfdc23
Revises: 7135202573f5
Create Date: 2025-11-08 16:07:43.451531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0f4b7cfdc23'
down_revision: Union[str, Sequence[str], None] = '7135202573f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('tags_name_key'), 'tags', type_='unique')
    op.drop_index(op.f('ix_templates_name'), table_name='templates')
    op.create_index(op.f('ix_templates_name'), 'templates', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_templates_name'), table_name='templates')
    op.create_index(op.f('ix_templates_name'), 'templates', ['name'], unique=True)
    op.create_unique_constraint(op.f('tags_name_key'), 'tags', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
