name: Python CI Backend

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build_and_test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.12'
            
            - name: Install Dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            
            - name: Lint with Ruff
              run: |
                ruff check .
            
            - name: Run tests with docker compose
              env:
                POSTGRES_USER: testuser
                POSTGRES_PASSWORD: testpass
                POSTGRES_DB: estrato_db_test
                SECRET_KEY: testsecretkey123
                ALGORITHM: HS256
                ACCESS_TOKEN_EXPIRE_MINUTES: 15
              run: docker compose -f docker-compose.yml run --rm tests